"use client"; import { useCallback, useEffect, useState } from "react"; import type { PlayerSession, RoomPlayer } from "@/features/rooms/room.types"; import { answerTrivia, getTriviaState } from "./trivia.api"; import type { TriviaState } from "./trivia.types"; import { useTriviaSocket } from "./use-trivia-socket";
export function TriviaPlayerPage({ code, player, session }: { code: string; player: RoomPlayer; session: PlayerSession }) {
 const [state,setState]=useState<TriviaState|null>(null); const [selection,setSelection]=useState<{questionId:string;index:number}|null>(null); const [error,setError]=useState(""); const update=useCallback((s:TriviaState)=>setState(s),[]); useTriviaSocket(code,update);
 useEffect(()=>{getTriviaState(code).then(setState).catch(e=>setError(e.message));},[code]);
 const selected=selection && selection.questionId===state?.question?.id?selection.index:null;
 async function choose(index:number){if(selected!==null||!state?.question)return; setSelection({questionId:state.question.id,index}); try{setState(await answerTrivia(session,index));}catch(e){setSelection(null);setError(e instanceof Error?e.message:"No pudimos responder");}}
 const answered=state?.answers[player.id]!==undefined;
 return <main className="phone-shell"><section className="phone-card trivia-player-card"><header><p className="phone-eyebrow">Sala {code} · {state?.roundNumber}/{state?.totalRounds}</p><strong>{player.nickname}</strong><b>{state?.scores[player.id]??0} pts</b></header>
 {state?.phase==="question"&&state.question?<><h1>{state.question.question}</h1><div className="trivia-options">{state.question.options.map((option,index)=><button key={option} disabled={answered} className={selected===index?"selected":""} onClick={()=>void choose(index)}><i>{String.fromCharCode(65+index)}</i>{option}</button>)}</div></>:state?.phase==="reveal"?<div className="trivia-feedback"><h1>{selected===state.correctIndex?"¡Correcto!":"Respuesta revelada"}</h1><p>{state.explanation}</p></div>:state?.phase==="finished"?<div className="trivia-feedback"><h1>{state.scores[player.id]??0} puntos</h1><p>Mira el resultado en la televisión.</p></div>:<div className="trivia-feedback"><h1>Prepárate</h1><p>La pregunta aparecerá en un momento.</p></div>}{error&&<p className="form-error">{error}</p>}</section></main>;
}
