import type { TriviaCategory, TriviaConfig } from "./trivia.types";
const CATEGORIES: Array<[TriviaCategory, string]> = [["history", "Historia"], ["geography", "Geografía"], ["science", "Ciencia"], ["math_logic", "Mate y lógica"], ["language", "Lengua"], ["art_literature", "Arte y literatura"], ["film_tv", "Cine y TV"], ["music", "Música"], ["sports", "Deportes"], ["technology", "Tecnología"], ["pop_culture", "Cultura popular"], ["mexico", "México"]];
const DIFFICULTIES = [["very_easy", "Muy fácil"], ["easy", "Fácil"], ["medium", "Media"], ["hard", "Difícil"], ["very_hard", "Muy difícil"]] as const;
export function TriviaConfigFields({ value, onChange }: { value: TriviaConfig; onChange: (value: TriviaConfig) => void }) {
  const patch = <K extends keyof TriviaConfig>(key: K, next: TriviaConfig[K]) => onChange({ ...value, [key]: next });
  const toggleCategory = (category: TriviaCategory) => patch("categories", value.categories.includes(category) ? value.categories.filter((item) => item !== category) : [...value.categories, category]);
  return <div className="trivia-config-fields">
    <label>Tipo de partida<div className="genre-picker"><button type="button" className={value.mode === "categories" ? "selected" : ""} onClick={() => patch("mode", "categories")}>Categorías</button><button type="button" className={value.mode === "custom" ? "selected" : ""} onClick={() => patch("mode", "custom")}>Tema personalizado</button></div></label>
    {value.mode === "categories" && <label>Categorías<div className="genre-picker"><button type="button" className={!value.categories.length ? "selected" : ""} onClick={() => patch("categories", [])}>Todas</button>{CATEGORIES.map(([category, label]) => <button type="button" key={category} className={value.categories.includes(category) ? "selected" : ""} onClick={() => toggleCategory(category)}>{label}</button>)}</div></label>}
    <label>{value.mode === "custom" ? "Tema e instrucciones" : "Instrucciones opcionales"}<textarea value={value.topic} onChange={(event) => patch("topic", event.target.value)} placeholder={value.mode === "custom" ? "Ej. Historia de las misiones Voyager, sólo instrumentación científica" : "Ej. Evita futbol y prioriza historia latinoamericana"} /></label>
    <label>Dificultades<div className="genre-picker"><button type="button" className={!value.difficulties.length ? "selected" : ""} onClick={() => patch("difficulties", [])}>Todas</button>{DIFFICULTIES.map(([difficulty, label]) => <button type="button" key={difficulty} className={value.difficulties.includes(difficulty) ? "selected" : ""} onClick={() => patch("difficulties", value.difficulties.includes(difficulty) ? value.difficulties.filter((item) => item !== difficulty) : [...value.difficulties, difficulty])}>{label}</button>)}</div></label>
    <div className="config-modal-row"><label>Preguntas<select value={value.rounds} onChange={(event) => patch("rounds", Number(event.target.value))}>{[5,10,15,20].map((number) => <option key={number}>{number}</option>)}</select></label><label>Tiempo<select value={value.answerDuration} onChange={(event) => patch("answerDuration", Number(event.target.value))}>{[10,15,20,30,45,60].map((number) => <option key={number} value={number}>{number} s</option>)}</select></label></div>
  </div>;
}
