create table if not exists public.trivia_question_history (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  entity_key text not null,
  fact_key text not null,
  question_text text not null,
  category text not null,
  difficulty text not null,
  source_title text not null,
  source_url text not null,
  created_at timestamptz not null default now(),
  unique (room_id, entity_key, fact_key)
);

create index if not exists trivia_question_history_room_created_idx
  on public.trivia_question_history (room_id, created_at desc);
